### ISSUE TITLE
Milestone 03 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/AutoTransformR#22]
Hi,

Thanks for your efforts in milestone 02 submission. I've just reviewed your submission and I have few comments/suggestions below.

- [x] Your package installation runs without any problems 
- [x] You have provided very comprehensive test cases that I cannot think of any more 
- [x] You have provided a vignette for the R package 
- [x] You have provided an open source license 
- [x] You have provided good documentation of your function 
I suggest you use `import OpenImageR` or `importFrom OpenImageR readImage` to make it easier for users not having to import the library themselves.

Thanks!
